### PR TITLE
Update Variants.ini

### PR DESCRIPTION
**Pull request by Belzedar94**
Fix the following variants:

- Orda // https://www.pychess.org/variant/orda

Add support for the following variants:

- 4x5 Chess // https://greenchess.net/rules.php?v=4x5-chess --> Solved draw
- 4x6 Chess // https://greenchess.net/rules.php?v=4x6-chess --> Solved draw
- 5x6 chess // https://greenchess.net/rules.php?v=5x6-chess
- Active chess // https://greenchess.net/rules.php?v=active
- Advanced Pawn chess // https://greenchess.net/rules.php?v=advanced-pawn
- Capture-all Chess // https://greenchess.net/rules.php?v=capture-all
- Capture chess // https://vchess.club/#/variants/Capture
- Checkless 6x6 Atomic // Checkless atomic on a 6x6 board
- Corner Rook Chess // https://greenchess.net/rules.php?v=corner-rook
- Crossing chess // https://vchess.club/#/variants/Crossing
- Diana Chess // https://greenchess.net/rules.php?v=diana (Kingside castling not working)
- Double Army chess // https://vchess.club/#/variants/Doublearmy
- Goth House // Gothic Chess + Crazyhouse
- Microchess // https://greenchess.net/rules.php?v=microchess
- Ordamirror // https://vchess.club/#/variants/Ordamirror
- Pawn Massacre chess // https://vchess.club/#/variants/Pawnmassacre
- Perfect chess // https://vchess.club/#/variants/Perfect
- Screen chess // https://vchess.club/#/variants/Screen (This version assumes 1 drop per turn instead of the whole blind setup as in vchess)
- Synochess // https://www.pychess.org/variant/synochess

### CODE REVIEW

**Comment by Belzedar94** [comment]
All of them have been tested locally in winboard without apparent issues, but I don't know if there is any way to further test.

**Comment by gbtami** [comment]
I think Ordamirror definition is incorrect (and can't be added still) because it needs a Falcon piece (QueenNi = "mQcN").

**Comment by Belzedar94** [comment]
You are totally right, the proposed implementation is based on Orda and does not include the Falcon piece. Please feel free to cut out the variant or to at least change the name and the comment.

**Comment by mtaktikos** [comment]
Well done! Have not tried your definition of Capture-all yet, but since it is based on giveaway I would not wonder if the side which loses all pieces is declared as the winner instead the loser. With adding the extinctionValue in the definition this can be corrected.

**Comment by ianfab** [comment]
Thanks for the PR. Here are a few comments, let me know if I should help with the changes.
- perfect chess, ordamirror: These variants can not be supported right now, and the specified start FENs are invalid (which is why the ffishjs tests are red). I think these two variants should be removed.
- active chess: Start FEN has no castling rights. Is this intended?
- captureall: The extinctionValue is not configured correctly. However, the config can be simplified to:
```
[captureall:extinction]
extinctionPieceTypes = *
```
- diana
  - promotion rules are incorrect (no queen promotion)
  - Using losalamos as base can also simplify the config
- screen: using placement as base can simplify config
- The `endgameEval` is obsolete. Your variants.ini might be based on an older version of the code where this was still in.

**Comment by Belzedar94** [comment]
I have created a new commit with all the following changes and fixes:

- Perfect chess has been removed.
- Active chess starting FEN has been fixed to allow castling rights.
- CaptureAll and Screen Chess have been simplified as per Fabian's recommendation.
- Diana chess fixed and simplified.
- Variants.ini rules and instructions updated to the latest version.

I also took the opportunity to add Empire and Shinobi chess. All credits to Fable, Couch Tomato and the Pychess team, as I only copied and pasted.

I'll shortly open a bug for the diana chess castling.

Thanks for reviewing :)

**Comment by Belzedar94** [comment]
Pushing another commit:

- Further fixes (Active chess FEN, Diana chess PieceToCharTable).
- Adding 2 more variants: Wildebeest and Maharajah2 (Balanced version of Maharajah and the Sepoys)

**Comment by ianfab** [comment]
Thanks for the updates. Since your branch has conflicts to my master branch, can you please rebase your branch? If you are not familiar with it, you can e.g. do it like this (assuming you named my repo `upstream`):
```
git checkout master
git fetch upstream
git rebase upstream/master
git push origin master -f
```
Furthermore it usually is recommended to not use master branch (in your repo) for feature development or pull requests, but that is up to you. There is also no problem with using it, you then just need to reset your branch again after it got merged to get it aligned with upstream.

**Comment by Belzedar94** [comment]
Branch rebased. Please confirm everything is okay now :)

**Comment by ianfab** [comment]
Thanks, merged.

**Pull request merged**
