### PR TITLE
Increase leapers' value for makpong

### PR DESCRIPTION
**Pull request by Fulmene**

### CODE REVIEW

**Comment by ianfab** [comment]
In principle looks good to me. However, I would prefer to make the condition that the leap is more than one square more explicit, e.g., by introducing an `int distance(Direction d)` function (e.g., in types.h) and then checking for distance(d) >= 2 instead of checking against all the specific directions. Converting `Direction` to a distance is not trivial, but something like in http://cpp.sh/3ec2e should work.

**Comment by Fulmene** [comment]
I see. That would help the code looks more readable. I'll verify distance conversion again also.

Do you want me to include it in this PR?

**Comment by ianfab** [comment]
Would be nice if you could include it in this PR if that is fine with you, otherwise I could also do the refactoring afterwards.

**Comment by ianfab** [comment]
Looks good. Can you please rebase and squash into a single commit (containing the test results in the message)?

**Comment by ianfab** [comment]
I rebased the branch on top of master. I will wait for the CI to finish, then it should be ready for merge.

**Comment by ianfab** [comment]
Congrats and thanks again, it is nice to see some progression in playing strength.

**Pull request merged**
