### PR TITLE
Update variants.ini

### PR DESCRIPTION
**Pull request by Snowmoondaphne**
Can i add a variant ?

### CODE REVIEW

**Comment by ianfab** [comment]
@Snowmoondaphne ?

**Comment by Snowmoondaphne** [comment]
Oh, thank you!

[pandemonium]
variantTemplate = shogi
pieceToCharTable = PNBRFSA.UV.+++++++.++Kpnbrfsa.uv.+++++++.++k
maxFile = 9
maxRank = 9
pocketSize = 9
startFen =
rnbsksbnr/2+a1+u1+f2/p1p1p1p1p/4v4/9/4V4/P1P1P1P1P/2+F1+U1+A2/RNBSKSBNR[] w
- - 0 1
customPiece1 = o:NA
customPiece2 = s:WF
customPiece3 = u:D
customPiece4 = w:DWF
castling = false
pieceDrops = true
capturesToHand = true
immobilityIllegal = true
soldier = p
knight = n
bishop = b
rook = r
king = k
queen = q
commoner = g
dragonHorse = h
bers = d
alfil = a
archbishop = c
chancellor = m
fers = f
wazir = v
centaur = t
promotionRank = 7
promotedPieceType = p:g n:o b:h r:d a:c v:m f:q s:w u:t
doubleStep = false
perpetualCheckIllegal = true
nMoveRule = 0
nFoldValue = loss
stalemateValue = loss

"A variant that combines drop and powerful pieces, and there is no draw."

Could this be a sufficient explanation?

2021년 11월 5일 (금) 오후 10:25, Fabian Fichter ***@***.***>님이 작성:

**Comment by ianfab** [comment]
Yes, that's fine. If you have a link to a rule description you can add that as well. Please update the PR accordingly, then I will merge it.

**Comment by Snowmoondaphne** [comment]
https://www.chessvariants.com/rules/pandemonium

Rule is here ! And I'm sorry but, what is PR ??

2021년 11월 5일 (금) 오후 11:57, Fabian Fichter ***@***.***>님이 작성:

**Comment by ianfab** [comment]
PR = pull request, i.e., the code you are requesting to merge/pull.

**Comment by Snowmoondaphne** [comment]
Ahh I see ٩(ˊᗜˋ*)و

2021년 11월 6일 (토) 오전 2:12, Fabian Fichter ***@***.***>님이 작성:

**Comment by Snowmoondaphne** [comment]
# A variant that combines drop and powerful pieces, and there is no draw
# https://www.chessvariants.com/rules/pandemonium
[pandemonium]
variantTemplate = shogi
pieceToCharTable = PNBRFSA.UV.+++++++.++Kpnbrfsa.uv.+++++++.++k
maxFile = 9
maxRank = 9
pocketSize = 9
startFen =
rnbsksbnr/2+a1+u1+f2/p1p1p1p1p/4v4/9/4V4/P1P1P1P1P/2+F1+U1+A2/RNBSKSBNR[] w
- - 0 1
customPiece1 = o:NA
customPiece2 = s:WF
customPiece3 = u:D
customPiece4 = w:DWF
castling = false
pieceDrops = true
capturesToHand = true
immobilityIllegal = true
soldier = p
knight = n
bishop = b
rook = r
king = k
queen = q
commoner = g
dragonHorse = h
bers = d
alfil = a
archbishop = c
chancellor = m
fers = f
wazir = v
centaur = t
promotionRank = 7
promotedPieceType = p:g n:o b:h r:d a:c v:m f:q s:w u:t
doubleStep = false
perpetualCheckIllegal = true
nMoveRule = 0
nFoldValue = loss
stalemateValue = loss

Like this ?

**Comment by Snowmoondaphne** [comment]
Ahh I see !

# A variant that combines drop and powerful pieces, and there is no draw #
https://www.chessvariants.com/rules/pandemonium
[pandemonium] variantTemplate = shogi pieceToCharTable =
PNBRFSA.UV.+++++++.++Kpnbrfsa.uv.+++++++.++k maxFile = 9 maxRank = 9
pocketSize = 9 startFen =
rnbsksbnr/2+a1+u1+f2/p1p1p1p1p/4v4/9/4V4/P1P1P1P1P/2+F1+U1+A2/RNBSKSBNR[] w
- - 0 1 customPiece1 = o:NA customPiece2 = s:WF customPiece3 = u:D
customPiece4 = w:DWF castling = false pieceDrops = true capturesToHand =
true immobilityIllegal = true soldier = p knight = n bishop = b rook = r
king = k queen = q commoner = g dragonHorse = h bers = d alfil = a
archbishop = c chancellor = m fers = f wazir = v centaur = t promotionRank
= 7 promotedPieceType = p:g n:o b:h r:d a:c v:m f:q s:w u:t doubleStep =
false perpetualCheckIllegal = true nMoveRule = 0 nFoldValue = loss
stalemateValue = loss
Like this ?

2021년 11월 6일 (토) 오전 2:12, Fabian Fichter ***@***.***>님이 작성:

**Comment by Snowmoondaphne** [comment]
Ahh I see !

# A variant that combines drop and powerful pieces, and there is no draw
#  https://www.chessvariants.com/rules/pandemonium
[pandemonium]
variantTemplate = shogi
pieceToCharTable = PNBRFSA.UV.+++++++.++Kpnbrfsa.uv.+++++++.++k
maxFile = 9
maxRank = 9
pocketSize = 9
startFen =
rnbsksbnr/2+a1+u1+f2/p1p1p1p1p/4v4/9/4V4/P1P1P1P1P/2+F1+U1+A2/RNBSKSBNR[] w
- - 0 1
customPiece1 = o:NA
customPiece2 = s:WF
customPiece3 = u:D
customPiece4 = w:DWF
castling = false
pieceDrops = true
capturesToHand = true
immobilityIllegal = true
soldier = p
knight = n
bishop = b
rook = r
king = k
queen = q
commoner = g
dragonHorse = h
bers = d
alfil = a
archbishop = c
chancellor = m
fers = f
wazir = v
centaur = t
promotionRank = 7
promotedPieceType = p:g n:o b:h r:d a:c v:m f:q s:w u:t
doubleStep = false
perpetualCheckIllegal = true
nMoveRule = 0
nFoldValue = loss
stalemateValue = loss

Like this ?

**Comment by Snowmoondaphne** [comment]
Ahh I see ! ٩(ˊᗜˋ*)و

# A variant that combines drop and powerful pieces, and there is no draw
#  https://www.chessvariants.com/rules/pandemonium
[pandemonium]
variantTemplate = shogi
pieceToCharTable = PNBRFSA.UV.+++++++.++Kpnbrfsa.uv.+++++++.++k
maxFile = 9
maxRank = 9
pocketSize = 9
startFen =
rnbsksbnr/2+a1+u1+f2/p1p1p1p1p/4v4/9/4V4/P1P1P1P1P/2+F1+U1+A2/RNBSKSBNR[] w
- - 0 1
customPiece1 = o:NA
customPiece2 = s:WF
customPiece3 = u:D
customPiece4 = w:DWF
castling = false
pieceDrops = true
capturesToHand = true
immobilityIllegal = true
soldier = p
knight = n
bishop = b
rook = r
king = k
queen = q
commoner = g
dragonHorse = h
bers = d
alfil = a
archbishop = c
chancellor = m
fers = f
wazir = v
centaur = t
promotionRank = 7
promotedPieceType = p:g n:o b:h r:d a:c v:m f:q s:w u:t
doubleStep = false
perpetualCheckIllegal = true
nMoveRule = 0
nFoldValue = loss
stalemateValue = loss

Like this ?

2021년 11월 6일 (토) 오전 2:12, Fabian Fichter ***@***.***>님이 작성:

**Pull request merged**
