### PR TITLE
Support xiangqi chasing rules

### PR DESCRIPTION
**Pull request by ianfab**
Implements AXF chasing rules, also see #55.

Chasing rules still need to be made configurable, this PR is mainly to collect feedback.

### CODE REVIEW

**Comment by xiangqishare** [comment]
Fen for testing
1.Black lose:
9/3kc4/3a5/3P5/9/4p4/9/4K4/9/3C5 w moves d6e6 e4d4 e6d6 d4e4
3k5/9/9/9/9/5p3/9/5p3/5K3/5C3 w moves f1e1 f2e2 e1f1 e2f2
3k5/9/9/9/9/9/3r5/9/9/3NK4 w moves d0c2 d3c3 c2d0 c3d3
5k3/9/9/9/9/1C7/1r7/9/1C7/4K4 w moves b4c4 b3c3 c4b4 c3b3
3k5/4P4/4b4/3C5/4c4/9/9/9/9/5K3 w moves d6e6 e7g5 e6d6 g5e7
3k5/9/9/9/9/9/9/9/cr1CAK3/9 w moves d1d3 b1b3 d3d1 b3b1
5k3/9/9/5C3/5c3/5C3/9/9/5p3/4K4 w moves f4d4 f5d5 d4f4 d5f5 f4d4
4k4/9/4b4/2c2nR2/9/9/9/9/9/3K5 w moves g6g5 f6g8 g5g6 g8f6
5k3/9/9/9/9/4c4/3r5/3NB4/4A4/4K4 w moves e0d0 e4d4 d0e0 d4e4
5k3/9/9/9/9/9/9/9/9/3NK1cr1 w moves d0c2 h0h2 c2d0 h2h0
5k3/9/9/9/9/1N2P1C2/9/4BC3/9/cr1RK4 w moves b4c2 b0c0 c2b4 c0b0
4k4/9/9/9/4n4/9/5C3/9/4N4/4K4 w moves e1g0 e9f9 g0e1 f9e9
3P5/3k5/3nn4/9/9/9/9/9/9/5K3 w moves d9e9 d8e8 e9d9 e8d8
4ck3/9/9/9/9/2r1R4/9/9/4A4/3AK4 w moves e4e3 c4c3 e3e4 c3c4
4k4/9/9/c1c6/9/r8/9/9/C8/3K5 w moves a1c1 a4c4 c1a1 c4a4

2.  draw 
9/4c4/3k5/3r5/9/9/4C4/9/4K4/3R5 w moves e3d3 d6e6 d3e3 e6d6
5k3/9/9/9/9/9/7r1/9/2nRA3c/4K4 w moves e1f0 h3h1 f0e1 h1h3
4ka3/c2R1R2c/4b4/9/9/9/9/9/9/4K4 w moves f8f6 f9e8 f6f8 e8f9
4k4/9/9/9/1r1N5/9/9/9/9/5K3 w moves d5c3 b5c5 c3e4 c5c4 e4d6 c4d4 d6f5 d4d5 f5e3 d5e5 e3c4 e5e4 c4d6 e4d4
3k5/6c2/9/7P1/6c2/6P2/9/9/9/5K3 w moves h6g6 g5h5 g6h6 h5g5
4ck3/9/9/9/9/2r1R1N2/6N2/9/4A4/3AK4 w moves e4e3 c4c3 e3e4 c3c4
5k3/9/9/c8/9/P1P6/9/2C6/9/3K5 w moves c2a2 a6c6 a2c2 c6a6
4k4/9/r1r6/9/PPPP5/9/9/9/1C7/5K3 w moves b1a1 a7b7 a1c1 c7d7 c1b1 b7a7 b1d1 d7c7 d1a1

**Comment by noobpwnftw** [comment]
5k3/9/9/5C3/5c3/5C3/9/9/5p3/4K4 w moves f4d4 f5d5 d4f4 d5f5 f4d4 is red lose in above list.

**Comment by zyshaoaok** [comment]
Chess rules issues！
[Chess rules issues.zip](https://github.com/ianfab/Fairy-Stockfish/files/8550403/Chess.rules.issues.zip)

**Comment by xiangqishare** [comment]
> Chess rules issues！ [Chess rules issues.zip](https://github.com/ianfab/Fairy-Stockfish/files/8550403/Chess.rules.issues.zip)

The author is implementing the rules.

**Comment by pluto2035** [comment]
It's a great job, many issues have been solved since the version (9d2637f)  , but the playing strength seems to be weaker than the last release version(with chasing problem) .  

It's the time to train a new NNUE file to fit for the new version.

Thanks and regards,
Pluto

**Pull request merged**
